spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaobaobao007/SpringCloud/tree/master/Config
          search-paths: /src/main/resources/springcloud-config
          username:
          password:
server:
  port: 8086