server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: service-consumer-feign
    cloud:
      config:
        discovery:
          enabled: true
          service-id: config-server
        profile: dev
        label: master
feign:
  hystrix:
    enabled: true